/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_asmita_convertgray_Convertgray */

#ifndef _Included_com_example_asmita_convertgray_Convertgray
#define _Included_com_example_asmita_convertgray_Convertgray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asmita_convertgray_Convertgray
 * Method:    convertgray
 * Signature: (II[I)[B
 */
JNIEXPORT jint JNICALL Java_com_example_asmita_convertgray_Convertgray_convertgray
  (JNIEnv*, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
